export const FETCH_AUTHORIZATION_DATA = 'FETCH_AUTHORIZATION_DATA';
export const AUTH_RESPONSE = 'AUTH_RESPONSE';
export const FETCH_GET_TASKS_LIST = 'FETCH_GET_TASKS_LIST';
export const SET_TASKS_LIST = 'SET_TASKS_LIST';