export const FETCH_GET_TASKS_LIST = 'FETCH_GET_TASKS_LIST';
export const SET_TASKS_LIST = 'SET_TASKS_LIST';
export const FETCH_STATUS_CHANGE = 'FETCH_STATUS_CHANGE';
export const STATUS_CHANGED_SUCCESSFUL = 'STATUS_CHANGED_SUCCESSFUL';
export const FETCH_SAVE_TASK_DATA = 'FETCH_SAVE_TASK_DATA';
export const SAVE_TASK_DATA_SUCCESSFUL = 'SAVE_TASK_DATA_SUCCESSFUL';
export const SAVE_NEW_TASK_DATA_SUCCESSFUL = 'SAVE_NEW_TASK_DATA_SUCCESSFUL';
export const ADD_TASK = 'ADD_TASK';